#Files and folders to exclude
exclude_patterns:
- "tests/"
- "spec/"
- "**/vendor/"
- ".coverage"
- ".coveragerc"
- ".test_auth.py"
- ".test_book.py"
- ".idea/**"
- "htmlcov/**"
- "thisvenv/**"
- "migrations/**"
- "**/htmlcov/**"