language: python
sudo: true
language: python
python:
  - "3.4"
services:
  - postgresql

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

addons:
  postgresql: "9.4"

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=qohoHiFmoZ5dJGvW3dD0qV9NVk066c3x6

before_script:
  - psql -c 'create database hello_books_test;' -U postgres
  - python source .env
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
- nosetests --with-coverage --cover-package=app


after_success:
- coveralls
