"""empty message

Revision ID: 2893f4d30f97
Revises: df457c195cbb
Create Date: 2018-06-22 11:33:26.430397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2893f4d30f97'
down_revision = 'df457c195cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('returned_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'returned_date')
    # ### end Alembic commands ###
