"""empty message

Revision ID: b078bcb0c822
Revises: 
Create Date: 2018-06-24 15:16:27.744076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b078bcb0c822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.alter_column('users', 'logged_in',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'logged_in',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
